import { Roboto } from "next/font/google";
import "@/assets/sass/global.scss";

const roboto = Roboto({
    subsets: ["latin"],
    display: "fallback",
    weight: ["400", "700"],
});

export const metadata = {
    title: "Newsletter Challenge",
    description: "Generated by create next app",
    robots: {
        index: false,
        follow: false,
    },
    themeColor: "#ffffff",
    icons: [
        { rel: "icon", sizes: "16x16", url: "/favicon-16x16.png" },
        { rel: "icon", sizes: "32x32", url: "/favicon-32x32.png" },
        {
            rel: "apple-touch-icon",
            sizes: "100x100",
            url: "/apple-touch-icon.png",
        },
        { rel: "manifest", url: "/site.webmanifest" },
        { rel: "mask-icon", url: "/safari-pinned-tab.svg" },
    ],
    manifest: "/site.webmanifest",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={roboto.className}>{children}</body>
        </html>
    );
}
